name: FlutterApp
description: Flutter 学习小例子。

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  carousel_slider: ^0.0.6
  flutter_simple_video_player: ^0.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  # 资源引用
  assets:
    - images/demo2.jpg
    - images/drawerBg.jpg
