name: TPFrontEnd
description: 基于 Flutter 构建的前端指示学习和经验分享 APP。

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  carousel_slider: ^1.0.1
  flutter_simple_video_player: ^0.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  # 资源引用
  assets:
    - images/demo2.jpg
    - images/drawerBg.jpg
